# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: client
    init: cd blog-app/client && npm i
    command: npm start

  - name: post service
    init: cd blog-app/posts && npm i
    command: npm start

  - name: comments service
    init: cd blog-app/comments && npm i
    command: npm start

  - name: query service
    init: cd blog-app/query && npm i
    command: npm start

  - name: moderation service
    init: cd blog-app/moderation && npm i
    command: npm start

  - name: event-bus service
    init: cd blog-app/event-bus && npm i
    command: npm start

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: client
    description: Client application
    port: 3000
    onOpen: notify
    visibility: public

  - name: posts
    description: Post service
    port: 4000
    onOpen: ignore
    visibility: public

  - name: comments
    description: Comments service
    port: 4001
    onOpen: ignore
    visibility: public

  - name: query
    description: Query service
    port: 4002
    onOpen: ignore
    visibility: public

  - name: moderation
    description: Moderation service
    port: 4003
    onOpen: ignore
    visibility: public

  - name: event-bus
    description: Event-Bus service
    port: 4005
    onOpen: ignore
    visibility: public
